language: php
dist: trusty
sudo: false

php:
  - 7.1

env:
  global:
    - DRUPAL_DB=sqlite://tmp/site.sqlite
    - DRUPAL_BASE_URL="http://127.0.0.1:8080"

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer --verbose install

script:
  - cd web

  # Install Drupal and start the web server.
  - ../vendor/bin/drush site-install --verbose --yes --db-url=$DRUPAL_DB
  - ../vendor/bin/drush runserver $DRUPAL_BASE_URL &
  - until curl -s $DRUPAL_BASE_URL; do true; done > /dev/null

  # Run unit and kernel tests.
  - cp ../.travis/config/phpunit.xml core/
  - ../vendor/bin/phpunit -c core --debug --verbose modules/custom

  # Check Drupal's coding standards.
  - ../vendor/bin/phpcs --config-set installed_paths /home/travis/build/juampynr/d8cidemovendor/drupal/coder/coder_sniffer
  - mkdir -p ../artifacts/phpcs
  - ../vendor/bin/phpcs --standard=Drupal --report=junit --report-junit=../artifacts/phpcs/phpcs.xml modules/custom
  - ../vendor/bin/phpcs --standard=DrupalPractice --report=junit --report-junit=../artifacts/phpcs/phpcs.xml modules/custom

