# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: juampynr/d8cidemo:latest

    working_directory: /var/www/html

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: robo add:coding-standards-deps

      - run: robo add:behat-deps

      - run: robo update:dependencies

      - run: robo setup:drupal admin admin

      - run:
          name: Run tests
          command: |
            cd web
            ../vendor/bin/phpunit -c core --debug modules/custom

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
